phrase = "DOST\ncooperation"
print(phrase + " is striving")
print(phrase.islower())
print(phrase.upper())
print(len(phrase))
print(phrase[3])
print(phrase.index("T"))
print(phrase.index("o"))
print(phrase.replace("cooperation","enterprise"))
print(phrase.upper())